//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG.res.strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFG.res.strings.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir gráfico continuo.
        /// </summary>
        internal static string _addContinousChartPanel_Header {
            get {
                return ResourceManager.GetString("_addContinousChartPanel.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir contenedor para gráficos.
        /// </summary>
        internal static string _addMenuItem_AddChartContainer {
            get {
                return ResourceManager.GetString("_addMenuItem.AddChartContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir contenedor para videos.
        /// </summary>
        internal static string _addMenuItem_AddVideoContainer {
            get {
                return ResourceManager.GetString("_addMenuItem.AddVideoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string _addMenuItem_Header {
            get {
                return ResourceManager.GetString("_addMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Vídeo.
        /// </summary>
        internal static string _añadirVideoMenuItem_Header {
            get {
                return ResourceManager.GetString("_añadirVideoMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string _fileMenuItem_Exit {
            get {
                return ResourceManager.GetString("_fileMenuItem.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string _fileMenuItem_Header {
            get {
                return ResourceManager.GetString("_fileMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string _fileMenuItem_Open {
            get {
                return ResourceManager.GetString("_fileMenuItem.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string _fileMenuItem_Save {
            get {
                return ResourceManager.GetString("_fileMenuItem.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedores ocultos.
        /// </summary>
        internal static string _layoutAnchorable_HiddenContainers {
            get {
                return ResourceManager.GetString("_layoutAnchorable.HiddenContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar datos desde XML.
        /// </summary>
        internal static string _loadXML_Header {
            get {
                return ResourceManager.GetString("_loadXML.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones y propiedades.
        /// </summary>
        internal static string _ObservationsAndProperties_Title {
            get {
                return ResourceManager.GetString("_ObservationsAndProperties.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click izquierdo y arrastrar para seleccionar un rango.
        /// </summary>
        internal static string _plotModel_Subtitle {
            get {
                return ResourceManager.GetString("_plotModel.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar rango.
        /// </summary>
        internal static string _plotModel_Title {
            get {
                return ResourceManager.GetString("_plotModel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Rango.
        /// </summary>
        internal static string _saveRange_Header {
            get {
                return ResourceManager.GetString("_saveRange.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar rango.
        /// </summary>
        internal static string _saveRange_Header1 {
            get {
                return ResourceManager.GetString("_saveRange.Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workbench.
        /// </summary>
        internal static string Window_Title {
            get {
                return ResourceManager.GetString("Window.Title", resourceCulture);
            }
        }
    }
}
